FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy scripts and requirements
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default command (can be overridden)
CMD ["python", "producer.py"]
